on: [ pull_request ]

name: Build RELION

jobs:
  build_on_x86_64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        altcpu: [ON, OFF]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update -q -y && \
          sudo apt-get install -q -y cmake git build-essential mpi-default-bin mpi-default-dev libfftw3-dev libtiff-dev libfltk1.3-dev
      - name: Build RELION for Linux x86_64
        run: mkdir build && cd build && cmake -DALTCPU=${{ matrix.altcpu }} .. && make

  build_on_aarch64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        altcpu: [ON, OFF]
    steps:
      - uses: actions/checkout@v3
      - name: Build RELION for Linux aarch64
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}:/relion" 
          install: |
            apt-get update -q -y
            apt-get install -q -y cmake git build-essential mpi-default-bin mpi-default-dev libfftw3-dev libtiff-dev libfltk1.3-dev
          run: |
            cd /relion
            mkdir build
            cd build
            cmake -DALTCPU=${{ matrix.altcpu }} ..
            make
